name: CI

on:
  push:
    branches: [ "feat/auth", "main" ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: app
          POSTGRES_PASSWORD: app
          POSTGRES_DB: app_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U app -d app_test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      APP_ENV: test
      APP_SECRET: test_secret
      DATABASE_URL: postgresql://app:app@127.0.0.1:5432/app_test?serverVersion=16&charset=utf8

      JWT_SECRET_KEY: config/jwt/private.pem
      JWT_PUBLIC_KEY: config/jwt/public.pem
      JWT_PASSPHRASE: test

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          extensions: mbstring, intl, pdo_pgsql
          coverage: none

      - name: Install deps
        run: composer install --no-interaction --prefer-dist

      - name: Create DB + migrate
        run: |
          php bin/console doctrine:database:create --if-not-exists --env=test
          php bin/console doctrine:migrations:migrate -n --allow-no-migration --env=test

      - name: Run tests
        run: php bin/phpunit
